<?php 
$server = 'localhost';
$username = 'root';
$password = '';
$db = 'conventsschool';
$conn = mysqli_connect($server,$username,$password,$db);

$stu_id = mysqli_real_escape_string($conn,$_GET['id']);
$selectStuData = mysqli_query($conn, "SELECT * FROM studentlist WHERE sl_id ='$stu_id'");
$DisplayStuData = mysqli_fetch_assoc($selectStuData);
$photo = $DisplayStuData['sl_photo'];

$sid = $DisplayStuData['sl_id'];
$selectstuclass = mysqli_query($conn, "SELECT * FROM studentclasslist WHERE SCL_stuID ='$sid' ORDER BY SCL_id DESC LIMIT 1");
$displaystuclass = mysqli_fetch_assoc($selectstuclass);
require('../../Assets/fpdf/fpdf.php');
// A4 width : 219 mm;
// default margian : 10mm each side;
// writable horizontal : 219-(10*2) = 189 mm;


$pdf = new FPDF('p','mm', 'A4');
$pdf -> AddPage();
// set font to arial, bold, 14pt
$pdf->SetFont('Arial','B',14);

//Cell(width, height, text, border, end line, [align]);
$pdf->SetFont('Arial','B',25);
$pdf->SetTextColor(8, 91, 207);
$pdf->Cell(0,10,'STUDENTS SUCCESS CONVENT',0,1,'C');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,4,'Sarbahda Bazar,Dih Road, Sarbahda, Gaya, Bihar',0,1,'C');
$pdf->SetFont('Arial','B',20);
$pdf->SetTextColor(207, 21, 8);
$pdf->Cell(0,20,'Registration Slip',0,1,'C');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'Academic Details ( Fill up by School )',1,1,'C');
$pdf->Cell(45,8,'Admission R. Number',1,0,'L');
$pdf->Cell(45,8,$DisplayStuData['sl_regi'],1,0,'L');
$pdf->Cell(45,8,'Admission Session',1,0,'L');
$pdf->Cell(55,8,$displaystuclass['SCL_session'],1,1,'L');
$pdf->Cell(20,8,'Class',1,0,'L');
$pdf->Cell(25,8,$displaystuclass['SCL_class'],1,0,'L');
$pdf->Cell(23,8,'Section',1,0,'L');
$pdf->Cell(20,8,'',1,0,'L');
$pdf->Cell(23,8,'Roll No',1,0,'L');
$pdf->Cell(20,8,$displaystuclass['SCL_rollno'],1,0,'L');
$pdf->Cell(23,8,'Join Date',1,0,'L');
$pdf->Cell(36,8,$DisplayStuData['sl_regi_date'],1,1,'L');
$pdf->Cell(23,8,'Transport',1,0,'L');
$pdf->Cell(23,8,$displaystuclass['SCL_Transport'],1,0,'L');
$pdf->Cell(40,8,'Transport Address',1,0,'L');
$pdf->Cell(0,8,$displaystuclass['SCL_TransportAddress'],1,1,'L');
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'STUDENTS DETAILS',0,1,'L');
$pdf->SetFont('Arial','',12);
$pdf->Cell(35,12,'Students Name',1,0,'L');
$pdf->Cell(110,12,$DisplayStuData['sl_name'],1,0,'L');
$pdf->Cell(45,48,'',1,0);
$pdf->Image("../Assets/StudentsPhoto/$photo",160,90,35,42);
$pdf->Cell(0,12,'',0,1);
$pdf->Cell(35,12,'Fathers Name',1,0,'L');
$pdf->Cell(110,12,$DisplayStuData['sl_fatherName'],1,1,'L');
$pdf->Cell(35,12,'Mothers Name',1,0,'L');
$pdf->Cell(110,12,$DisplayStuData['sl_motherName'],1,1,'L');
$pdf->Cell(35,12,'Gauration Name',1,0,'L');
$pdf->Cell(110,12,$DisplayStuData['sl_gradName'],1,1,'L');
$pdf->Cell(20,8,'DOB',1,0,'L');
$pdf->Cell(35,8,$DisplayStuData['sl_dob'],1,0,'L');
$pdf->Cell(20,8,'Gender',1,0,'L');
$pdf->Cell(24,8,$DisplayStuData['sl_gender'],1,0,'L');
$pdf->Cell(20,8,'Category',1,0,'L');
$pdf->Cell(26,8,$DisplayStuData['sl_category'],1,0,'L');
$pdf->Cell(20,8,'Religion',1,0,'L');
$pdf->Cell(25,8,$DisplayStuData['sl_nationality'],1,1,'L');
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'CONTACTS DETAILS',0,1,'L');
$pdf->SetFont('Arial','',12);
$pdf->Cell(39,8,'Current Address',1,0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(150,8,$DisplayStuData['sl_caddress'],1,1,'L');
$pdf->SetFont('Arial','',12);
$pdf->Cell(39,8,'Permanent Address',1,0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(150,8,$DisplayStuData['sl_paddress'],1,1,'L');
$pdf->SetFont('Arial','',12);
$pdf->Cell(45,8,'Contact Number',1,0,'L');
$pdf->Cell(50,8,$DisplayStuData['sl_contentNumber'],1,0,'L');
$pdf->Cell(44,8,'A. Contact Number',1,0,'L');
$pdf->Cell(50,8,$DisplayStuData['sl_alternativeNumber'],1,1,'L');
$pdf->Cell(40,8,'Whatsapp Number',1,0,'L');
$pdf->Cell(35,8,$DisplayStuData['sl_whatsappNumber'],1,0,'L');
$pdf->Cell(25,8,'Email',1,0,'L');
$pdf->Cell(89,8,$DisplayStuData['sl_emailAddress'],1,1,'L');
$pdf->Cell(0,10,'',0,1,'L');
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,8,'SCHOOL INSTRUCTION ( T&C )',0,1,'L');
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'1. Students Come in Your School Uniform.',0,1,'L');
$pdf->Output();
?>